import Head from 'next/head'
import { useCallback, useEffect, useState } from 'react'
import styles from '../styles/header.module.css'
import Link from 'next/link'
import pagetitle from '../pages/[pagetitle]'



export default function Header() {
    const [count,setCount]=useState(0)

    const updateCount = useCallback(()=>{
      setCount((old)=>old-1)
    },[])
  
    const [name, setName]=useState("now loading ...")
    useEffect(()=>{
      fetch("/api/hello")
      .then((res)=>res.json())
      .then((
        data
      )=>{
        setName(data.name)
      })
    },[count])
  
    return (
        <>
        <Head>
        <title>{pagetitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.header}>
            <h1 className={styles.title}>
            {pagetitle} <button onClick={updateCount}>{count}</button>
            </h1>
        <nav className={styles.nav}>
            <Link href={"/"}><a>HOME</a></Link>
            <Link href={"/contact"}><a>CONTACT</a></Link>
            <Link href={"/hello"}><a>HELLO</a></Link>
        </nav>
        </div>
        </>
    )
}