import Head from 'next/head'
import { useCallback, useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'


export default function Header() {
    const [count,setCount]=useState(0)

    const updateCount = useCallback(()=>{
      setCount((old)=>old-1)
    },[])
  
    const [name, setName]=useState("now loading ...")
    useEffect(()=>{
      fetch("../pages/api/hello")
      .then((res)=>res.json())
      .then((
        data
      )=>{
        setName(data.name)
      })
    },[count])
  
    return (
        <>
        <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.header}>
            <h1 className={styles.title}>
            {name} <button onClick={updateCount}>{count}</button>
            </h1>

            <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.js</code>
         </p>
        </div>
        </>
    )
}