import Head from 'next/head'
import Link from 'next/link'
import { Nav, Navbar, Container, NavDropdown } from 'react-bootstrap'


export default function Header() {  
    return (
        <>
        <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar className={`bg-gradient-to-r from-blue-800 to-white`}>
  <Container>
  <Link href={"/"}><Navbar.Brand>Kenji Kobayashi</Navbar.Brand></Link>
  <Navbar.Toggle aria-controls="responsive-navbar-nav" />
  <Navbar.Collapse id="responsive-navbar-nav">
    <Nav className="me-auto">
    <Nav.Link href="/">Home</Nav.Link>
    <Nav.Link href="/profile">Profile</Nav.Link>
      <NavDropdown title="More on" id="collasible-nav-dropdown">
        <NavDropdown.Item href="/works">Works</NavDropdown.Item>
        <NavDropdown.Item href="/achievements">Achievements</NavDropdown.Item>
        <NavDropdown.Item href="/soccer">Soccer</NavDropdown.Item>
      </NavDropdown>
      <Nav.Link href="/contact">Contact</Nav.Link>
    </Nav>
        <a className="no-underline text-blue-800">個人的なサイトです</a>
  </Navbar.Collapse>
  </Container>
</Navbar>
        </>
    )
}