import Head from 'next/head'
import Image from 'next/image'
import { useCallback, useEffect, useState } from 'react'
import Card from '../components/card'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [count,setCount]=useState(0)

  const updateCount = useCallback(()=>{
    setCount((old)=>old-1)
  },[])

  const [name, setName]=useState("wow")
  useEffect(()=>{
    fetch("/api/hello")
    .then((res)=>res.json())
    .then((
      data
    )=>{
      setName(data.name)
    })
  },[count])


  return (
    <div className={styles.container}>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        {name} <button onClick={updateCount}>{count}</button>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <Card title="hello"/> 

          <Card title="example" href="https://github.com/vercel/next.js/tree/canary/examples">
            {/** childrenはこの中のこと */}
            <img src="/vercel.svg"/>
          </Card>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
